// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/base/Footer.vue')['default']
    BaseTitle: typeof import('./src/components/base/Title.vue')['default']
    CertificateItem: typeof import('./src/components/certificate/Item.vue')['default']
    GithubCorner: typeof import('./src/components/GithubCorner.vue')['default']
    HelloResume: typeof import('./src/components/HelloResume.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon.vue')['default']
    IRiFileInfoLine: typeof import('virtual:vite-icons/ri/file-info-line')['default']
    IRiFileTextLine: typeof import('virtual:vite-icons/ri/file-text-line')['default']
    IRiGithubLine: typeof import('virtual:vite-icons/ri/github-line')['default']
    IRiHome2Line: typeof import('virtual:vite-icons/ri/home2-line')['default']
    IRiMoonLine: typeof import('virtual:vite-icons/ri/moon-line')['default']
    IRiSideBarLine: typeof import('virtual:vite-icons/ri/side-bar-line')['default']
    IRiSunLine: typeof import('virtual:vite-icons/ri/sun-line')['default']
    IRiTranslate: typeof import('virtual:vite-icons/ri/translate')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    ResumeAll: typeof import('./src/components/resume/All.vue')['default']
    ResumeCertificate: typeof import('./src/components/resume/Certificate.vue')['default']
    ResumeEducation: typeof import('./src/components/resume/Education.vue')['default']
    ResumeFooter: typeof import('./src/components/resume/Footer.vue')['default']
    ResumeHeader: typeof import('./src/components/resume/Header.vue')['default']
    ResumeOther: typeof import('./src/components/resume/Other.vue')['default']
    ResumeProject: typeof import('./src/components/resume/Project.vue')['default']
    ResumeSkill: typeof import('./src/components/resume/Skill.vue')['default']
  }
}

export { }
