/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressBar: typeof import('./components/AddressBar.vue')['default']
    AddressBarInput: typeof import('./components/AddressBarInput.vue')['default']
    AppCommandPalette: typeof import('./components/AppCommandPalette.vue')['default']
    AppMenubar: typeof import('./components/AppMenubar.vue')['default']
    AppMoreMenu: typeof import('./components/AppMoreMenu.vue')['default']
    AppToasts: typeof import('./components/AppToasts.vue')['default']
    BaseFooter: typeof import('./components/base/Footer.vue')['default']
    BaseTitle: typeof import('./components/base/Title.vue')['default']
    BottomMenu: typeof import('./components/BottomMenu.vue')['default']
    CertificateItem: typeof import('./components/certificate/Item.vue')['default']
    HelloResume: typeof import('./components/HelloResume.vue')['default']
    IconifyIcon: typeof import('./components/IconifyIcon.vue')['default']
    InfoPageShell: typeof import('./components/InfoPageShell.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    OnboardingDialog: typeof import('./components/OnboardingDialog.vue')['default']
    OnboardingSteps: typeof import('./components/OnboardingSteps.vue')['default']
    ProjectItem: typeof import('./components/project/Item.vue')['default']
    ResumeAll: typeof import('./components/resume/All.vue')['default']
    ResumeCertificate: typeof import('./components/resume/Certificate.vue')['default']
    ResumeContactGitHub: typeof import('./components/resume/Contact/GitHub.vue')['default']
    ResumeContactPhone: typeof import('./components/resume/Contact/Phone.vue')['default']
    ResumeEducation: typeof import('./components/resume/Education.vue')['default']
    ResumeEmptyState: typeof import('./components/ResumeEmptyState.vue')['default']
    ResumeFooter: typeof import('./components/resume/Footer.vue')['default']
    ResumeHeader: typeof import('./components/resume/Header.vue')['default']
    ResumeInterests: typeof import('./components/resume/Interests.vue')['default']
    ResumeLanguages: typeof import('./components/resume/Languages.vue')['default']
    ResumeMigrationPanel: typeof import('./components/ResumeMigrationPanel.vue')['default']
    ResumeOther: typeof import('./components/resume/Other.vue')['default']
    ResumePreview: typeof import('./components/ResumePreview.vue')['default']
    ResumeProject: typeof import('./components/resume/Project.vue')['default']
    ResumePublications: typeof import('./components/resume/Publications.vue')['default']
    ResumeReferences: typeof import('./components/resume/References.vue')['default']
    ResumeSkill: typeof import('./components/resume/Skill.vue')['default']
    ResumeSourceDialog: typeof import('./components/ResumeSourceDialog.vue')['default']
    ResumeTemplate: typeof import('./components/ResumeTemplate.vue')['default']
    ResumeVolunteer: typeof import('./components/resume/Volunteer.vue')['default']
    ResumeWork: typeof import('./components/resume/Work.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    WorkItem: typeof import('./components/work/Item.vue')['default']
  }
}
