/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/editor': RouteRecordInfo<
      '/editor',
      '/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore': RouteRecordInfo<
      '/explore',
      '/explore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy': RouteRecordInfo<
      '/privacy',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resume': RouteRecordInfo<
      '/resume',
      '/resume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support': RouteRecordInfo<
      '/support',
      '/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user': RouteRecordInfo<
      '/user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/editor.vue': {
      routes:
        | '/editor'
      views:
        | never
    }
    'src/pages/explore.vue': {
      routes:
        | '/explore'
      views:
        | never
    }
    'src/pages/privacy.vue': {
      routes:
        | '/privacy'
      views:
        | never
    }
    'src/pages/resume.vue': {
      routes:
        | '/resume'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/support.vue': {
      routes:
        | '/support'
      views:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | '/user'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
