/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressBar: typeof import('./components/AddressBar.vue')['default']
    AddressBarInput: typeof import('./components/AddressBarInput.vue')['default']
    BaseFooter: typeof import('./components/base/Footer.vue')['default']
    BaseTitle: typeof import('./components/base/Title.vue')['default']
    BottomMenu: typeof import('./components/BottomMenu.vue')['default']
    CertificateItem: typeof import('./components/certificate/Item.vue')['default']
    DialogCopied: typeof import('./components/DialogCopied.vue')['default']
    HelloResume: typeof import('./components/HelloResume.vue')['default']
    IconifyIcon: typeof import('./components/IconifyIcon.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    ProjectItem: typeof import('./components/project/Item.vue')['default']
    ResumeAll: typeof import('./components/resume/All.vue')['default']
    ResumeCertificate: typeof import('./components/resume/Certificate.vue')['default']
    ResumeContactGitHub: typeof import('./components/resume/Contact/GitHub.vue')['default']
    ResumeContactPhone: typeof import('./components/resume/Contact/Phone.vue')['default']
    ResumeEducation: typeof import('./components/resume/Education.vue')['default']
    ResumeFooter: typeof import('./components/resume/Footer.vue')['default']
    ResumeHeader: typeof import('./components/resume/Header.vue')['default']
    ResumeOther: typeof import('./components/resume/Other.vue')['default']
    ResumeProject: typeof import('./components/resume/Project.vue')['default']
    ResumeSkill: typeof import('./components/resume/Skill.vue')['default']
    ResumeTemplate: typeof import('./components/ResumeTemplate.vue')['default']
    ResumeWork: typeof import('./components/resume/Work.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    WorkItem: typeof import('./components/work/Item.vue')['default']
    YlfBottomMenu: typeof import('./../node_modules/.pnpm/@yunlefun+vue-components@0.0.5-beta.4/node_modules/@yunlefun/vue-components/dist/runtime/components/YlfBottomMenu.vue')['default']
    YlfBottomMenuItem: typeof import('./../node_modules/.pnpm/@yunlefun+vue-components@0.0.5-beta.4/node_modules/@yunlefun/vue-components/dist/runtime/components/YlfBottomMenuItem.vue')['default']
  }
}
