/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/base/Footer.vue')['default']
    BaseTitle: typeof import('./components/base/Title.vue')['default']
    CertificateItem: typeof import('./components/certificate/Item.vue')['default']
    HelloResume: typeof import('./components/HelloResume.vue')['default']
    IconifyIcon: typeof import('./components/IconifyIcon.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    ProjectItem: typeof import('./components/project/Item.vue')['default']
    ResumeAll: typeof import('./components/resume/All.vue')['default']
    ResumeCertificate: typeof import('./components/resume/Certificate.vue')['default']
    ResumeEducation: typeof import('./components/resume/Education.vue')['default']
    ResumeFooter: typeof import('./components/resume/Footer.vue')['default']
    ResumeHeader: typeof import('./components/resume/Header.vue')['default']
    ResumeOther: typeof import('./components/resume/Other.vue')['default']
    ResumeProject: typeof import('./components/resume/Project.vue')['default']
    ResumeSkill: typeof import('./components/resume/Skill.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
  }
}
